"""made power rating nullable

Revision ID: f8cdf661f866
Revises: e35d7ffe379b
Create Date: 2025-02-20 12:28:26.723698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cdf661f866'
down_revision = 'e35d7ffe379b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronics', schema=None) as batch_op:
        batch_op.alter_column('power_rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronics', schema=None) as batch_op:
        batch_op.alter_column('power_rating',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
